#pragma once

#include <iostream>
#include "expression.h"
#include "expr_dup_checker.h"

class c_const_tester {
public:

    void test_expr_tree() {
        el::expression expr1;
        //expr1.from_string("(3 + 5 - 8 * 2 / 9) * 6 / (1 + (7 - 2))");
        expr1.from_string("1 + 2 + 3");
        std::cout << expr1.to_string() << std::endl;
        std::vector<el::s_token> postfix;
        el::expression::infix2postfix(expr1.m_tokens, postfix);
        expr1.swap_tokens(std::move(postfix));
        std::cout << "postfix: " << expr1.to_string() << std::endl;

        el::expr_tree et1;
        et1.construct_from_postfix(expr1.m_tokens);

        el::expression expr2;
        //expr2.from_string("6 * (3 + 5 - 2 * 8 / 9)  / (7-2+1)");
        expr2.from_string("3 + (1 + 2)");
        std::cout << expr2.to_string() << std::endl;
        postfix.clear();
        el::expression::infix2postfix(expr2.m_tokens, postfix);
        expr2.swap_tokens(std::move(postfix));
        std::cout << "postfix: " << expr2.to_string() << std::endl;

        el::expr_tree et2;
        et2.construct_from_postfix(expr2.m_tokens);

        std::cout << "et1.is_isomorphic(et2): " << et1.is_isomorphic(et2) << std::endl;
        std::cout << "et2.is_isomorphic(et1): " << et2.is_isomorphic(et1) << std::endl;

        getchar();
    }

    void test_dup_checker() {
        std::vector<std::string> exprs;

        // at least 2019 duplications (evaluated by excel)

        exprs.push_back("3 + 4 - 5 * 6");
        exprs.push_back("7 / 8 + 9 - 1");
        exprs.push_back("2 * 3 / 4 + 5");
        exprs.push_back("6 * 7 / 8 + 9");
        exprs.push_back("1 * 2 / 3 + 4");
        exprs.push_back("5 + 6 - 7 * 8");
        exprs.push_back("9 - 1 * 2 / 3");
        exprs.push_back("4 + 5 - 6 * 7");
        exprs.push_back("8 / 9 + 1 - 2");
        exprs.push_back("3 + 4 - 5 * 6");
        exprs.push_back("7 + 8 - 9 * 1");
        exprs.push_back("2 * 3 / 4 + 5");
        exprs.push_back("6 * 7 / 8 + 9");
        exprs.push_back("1 - 2 * 3 / 4");
        exprs.push_back("5 * 6 / 7 + 8");
        exprs.push_back("9 + 1 - 2 * 3");
        exprs.push_back("4 + 5 - 6 * 7");
        exprs.push_back("8 + 9 - 1 * 2");
        exprs.push_back("3 / 4 + 5 - 6");
        exprs.push_back("7 * 8 / 9 + 1");
        exprs.push_back("2 + 3 - 4 * 5");
        exprs.push_back("6 / 7 + 8 - 9");
        exprs.push_back("1 * 2 / 3 + 4");
        exprs.push_back("5 + 6 - 7 * 8");
        exprs.push_back("9 * 1 / 2 + 3");
        exprs.push_back("4 * 5 / 6 + 7");
        exprs.push_back("8 - 9 * 1 / 2");
        exprs.push_back("3 / 4 + 5 - 6");
        exprs.push_back("7 * 8 / 9 + 1");
        exprs.push_back("2 - 3 * 4 / 5");
        exprs.push_back("6 / 7 + 8 - 9");
        exprs.push_back("1 * 2 / 3 + 4");
        exprs.push_back("5 * 6 / 7 + 8");
        exprs.push_back("9 - 1 * 2 / 3");
        exprs.push_back("4 * 5 / 6 + 7");
        exprs.push_back("8 + 9 - 1 * 2");
        exprs.push_back("3 - 4 * 5 / 6");
        exprs.push_back("7 + 8 - 9 * 1");
        exprs.push_back("2 - 3 * 4 / 5");
        exprs.push_back("6 + 7 - 8 * 9");
        exprs.push_back("1 / 2 + 3 - 4");
        exprs.push_back("5 / 6 + 7 - 8");
        exprs.push_back("9 / 1 + 2 - 3");
        exprs.push_back("4 / 5 + 6 - 7");
        exprs.push_back("8 * 9 / 1 + 2");
        exprs.push_back("3 / 4 + 5 - 6");
        exprs.push_back("7 * 8 / 9 + 1");
        exprs.push_back("2 - 3 * 4 / 5");
        exprs.push_back("6 / 7 + 8 - 9");
        exprs.push_back("1 / 2 + 3 - 4");
        exprs.push_back("5 + 6 - 7 * 8");
        exprs.push_back("9 - 1 * 2 / 3");
        exprs.push_back("4 * 5 / 6 + 7");
        exprs.push_back("8 * 9 / 1 + 2");
        exprs.push_back("3 + 4 - 5 * 6");
        exprs.push_back("7 / 8 + 9 - 1");
        exprs.push_back("2 + 3 - 4 * 5");
        exprs.push_back("6 - 7 * 8 / 9");
        exprs.push_back("1 * 2 / 3 + 4");
        exprs.push_back("5 + 6 - 7 * 8");
        exprs.push_back("9 * 1 / 2 + 3");
        exprs.push_back("4 + 5 - 6 * 7");
        exprs.push_back("8 - 9 * 1 / 2");
        exprs.push_back("3 - 4 * 5 / 6");
        exprs.push_back("7 / 8 + 9 - 1");
        exprs.push_back("2 * 3 / 4 + 5");
        exprs.push_back("6 * 7 / 8 + 9");
        exprs.push_back("1 - 2 * 3 / 4");
        exprs.push_back("5 / 6 + 7 - 8");
        exprs.push_back("9 * 1 / 2 + 3");
        exprs.push_back("4 - 5 * 6 / 7");
        exprs.push_back("8 - 9 * 1 / 2");
        exprs.push_back("3 + 4 - 5 * 6");
        exprs.push_back("7 * 8 / 9 + 1");
        exprs.push_back("2 / 3 + 4 - 5");
        exprs.push_back("6 - 7 * 8 / 9");
        exprs.push_back("1 / 2 + 3 - 4");
        exprs.push_back("5 / 6 + 7 - 8");
        exprs.push_back("9 / 1 + 2 - 3");
        exprs.push_back("4 - 5 * 6 / 7");
        exprs.push_back("8 / 9 + 1 - 2");
        exprs.push_back("3 + 4 - 5 * 6");
        exprs.push_back("7 / 8 + 9 - 1");
        exprs.push_back("2 - 3 * 4 / 5");
        exprs.push_back("6 - 7 * 8 / 9");
        exprs.push_back("1 + 2 - 3 * 4");
        exprs.push_back("5 + 6 - 7 * 8");
        exprs.push_back("9 / 1 + 2 - 3");
        exprs.push_back("4 / 5 + 6 - 7");
        exprs.push_back("8 - 9 * 1 / 2");
        exprs.push_back("3 / 4 + 5 - 6");
        exprs.push_back("7 + 8 - 9 * 1");
        exprs.push_back("2 + 3 - 4 * 5");
        exprs.push_back("6 / 7 + 8 - 9");
        exprs.push_back("1 * 2 / 3 + 4");
        exprs.push_back("5 * 6 / 7 + 8");
        exprs.push_back("9 / 1 + 2 - 3");
        exprs.push_back("4 * 5 / 6 + 7");
        exprs.push_back("8 - 9 * 1 / 2");
        exprs.push_back("3 - 4 * 5 / 6");

        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 * 2 / 3");
        exprs.push_back("4 / 5 + 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 * 2 / 3");
        exprs.push_back("4 / 5 + 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 / 5 + 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 * 2 / 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 * 8 / 9");
        exprs.push_back("1 * 2 / 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 * 8 / 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 * 8 / 9");
        exprs.push_back("1 * 2 / 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 * 2 / 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 * 8 / 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 * 2 / 3");
        exprs.push_back("4 / 5 + 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 * 2 / 3");
        exprs.push_back("4 / 5 + 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 / 5 + 6");
        exprs.push_back("7 * 8 / 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 * 8 / 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 * 2 / 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 / 5 + 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 * 8 / 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 * 8 / 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 / 5 + 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 * 2 / 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 * 8 / 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 / 5 + 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 * 8 / 9");
        exprs.push_back("1 * 2 / 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 * 8 / 9");
        exprs.push_back("1 * 2 / 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 / 5 + 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 * 2 / 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 * 2 / 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 * 8 / 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 / 5 + 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 * 2 / 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 / 5 + 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 * 8 / 9");
        exprs.push_back("1 * 2 / 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 * 2 / 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 * 2 / 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 * 8 / 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 / 5 + 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 * 2 / 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 * 2 / 3");
        exprs.push_back("4 / 5 + 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 / 5 + 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 * 8 / 9");
        exprs.push_back("1 * 2 / 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 * 8 / 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 * 2 / 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 * 2 / 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 * 8 / 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 / 5 + 6");
        exprs.push_back("7 * 8 / 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 * 8 / 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 * 2 / 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 * 8 / 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 * 8 / 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 * 8 / 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 / 5 + 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 * 2 / 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 / 5 + 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 * 2 / 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 * 8 / 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 / 5 + 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 * 2 / 3");
        exprs.push_back("4 / 5 + 6");
        exprs.push_back("7 * 8 / 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 / 5 + 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 * 2 / 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 / 5 + 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 * 8 / 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 * 2 / 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 * 8 / 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 * 8 / 9");
        exprs.push_back("1 * 2 / 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 / 5 + 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 / 5 + 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 * 8 / 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 / 5 + 6");
        exprs.push_back("7 * 8 / 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 * 8 / 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 / 5 + 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 * 8 / 9");
        exprs.push_back("1 * 2 / 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 * 2 / 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 * 2 / 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 * 8 / 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 / 5 + 6");
        exprs.push_back("7 * 8 / 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 * 2 / 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 / 5 + 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 * 8 / 9");
        exprs.push_back("1 * 2 / 3");
        exprs.push_back("4 / 5 + 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 * 2 / 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 * 8 / 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 * 8 / 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 / 5 + 6");
        exprs.push_back("7 * 8 / 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 / 5 + 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 * 8 / 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 / 5 + 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 * 2 / 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 / 5 + 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 * 8 / 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 / 5 + 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 / 5 + 6");
        exprs.push_back("7 * 8 / 9");
        exprs.push_back("1 * 2 / 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 * 8 / 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 / 5 + 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 * 8 / 9");
        exprs.push_back("1 * 2 / 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 * 8 / 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 * 8 / 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 * 8 / 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 * 2 / 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 * 8 / 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 * 8 / 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 * 2 / 3");
        exprs.push_back("4 / 5 + 6");
        exprs.push_back("7 * 8 / 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 * 2 / 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 / 5 + 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 / 5 + 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 / 5 + 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 * 8 / 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 * 8 / 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 / 5 + 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 / 5 + 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 * 2 / 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 * 8 / 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 * 8 / 9");
        exprs.push_back("1 * 2 / 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 * 2 / 3");
        exprs.push_back("4 / 5 + 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 / 5 + 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 * 2 / 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 / 5 + 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 / 5 + 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 / 5 + 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 * 2 / 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 * 8 / 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 * 8 / 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 * 2 / 3");
        exprs.push_back("4 / 5 + 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 * 2 / 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 / 5 + 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 / 5 + 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 * 2 / 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 / 5 + 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 * 2 / 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 * 8 / 9");
        exprs.push_back("1 * 2 / 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 / 5 + 6");
        exprs.push_back("7 * 8 / 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 * 8 / 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 * 2 / 3");
        exprs.push_back("4 / 5 + 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 * 2 / 3");
        exprs.push_back("4 / 5 + 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 / 5 + 6");
        exprs.push_back("7 * 8 / 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 / 5 + 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 * 2 / 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 * 2 / 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 * 8 / 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 / 5 + 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 * 2 / 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 * 2 / 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 / 5 + 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 * 2 / 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 * 8 / 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 / 5 + 6");
        exprs.push_back("7 * 8 / 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 * 2 / 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 / 5 + 6");
        exprs.push_back("7 * 8 / 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 * 8 / 9");
        exprs.push_back("1 * 2 / 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 * 2 / 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 * 8 / 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 * 8 / 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 / 5 + 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 / 5 + 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 / 5 + 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 / 5 + 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 / 5 + 6");
        exprs.push_back("7 * 8 / 9");
        exprs.push_back("1 * 2 / 3");
        exprs.push_back("4 / 5 + 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 / 5 + 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 * 2 / 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 * 8 / 9");
        exprs.push_back("1 * 2 / 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 * 2 / 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 * 2 / 3");
        exprs.push_back("4 / 5 + 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 / 5 + 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 * 8 / 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 * 2 / 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 * 8 / 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 / 5 + 6");
        exprs.push_back("7 * 8 / 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 * 8 / 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 * 8 / 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 / 5 + 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 / 5 + 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 / 8 + 9");
        exprs.push_back("1 * 2 / 3");
        exprs.push_back("4 / 5 + 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 * 2 / 3");
        exprs.push_back("4 + 5 - 6");
        exprs.push_back("7 - 8 * 9");
        exprs.push_back("1 * 2 / 3");
        exprs.push_back("4 - 5 * 6");
        exprs.push_back("7 * 8 / 9");
        exprs.push_back("1 - 2 * 3");
        exprs.push_back("4 / 5 + 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 / 2 + 3");
        exprs.push_back("4 * 5 / 6");
        exprs.push_back("7 + 8 - 9");
        exprs.push_back("1 + 2 - 3");
        exprs.push_back("4 / 5 + 6");

        exprs.push_back("6 * 7");
        exprs.push_back("8 * 9");
        exprs.push_back("1 + 2");
        exprs.push_back("3 - 4");
        exprs.push_back("5 * 6");
        exprs.push_back("7 - 8");
        exprs.push_back("9 * 1");
        exprs.push_back("2 * 3");
        exprs.push_back("4 / 5");
        exprs.push_back("6 + 7");
        exprs.push_back("8 + 9");
        exprs.push_back("1 - 2");
        exprs.push_back("3 * 4");
        exprs.push_back("5 * 6");
        exprs.push_back("7 - 8");
        exprs.push_back("9 - 1");
        exprs.push_back("2 / 3");
        exprs.push_back("4 - 5");
        exprs.push_back("6 / 7");
        exprs.push_back("8 + 9");
        exprs.push_back("1 / 2");
        exprs.push_back("3 + 4");
        exprs.push_back("5 + 6");
        exprs.push_back("7 - 8");
        exprs.push_back("9 + 1");
        exprs.push_back("2 + 3");
        exprs.push_back("4 - 5");
        exprs.push_back("6 * 7");
        exprs.push_back("8 * 9");
        exprs.push_back("1 + 2");
        exprs.push_back("3 - 4");
        exprs.push_back("5 * 6");
        exprs.push_back("7 / 8");
        exprs.push_back("9 - 1");
        exprs.push_back("2 - 3");
        exprs.push_back("4 + 5");
        exprs.push_back("6 / 7");
        exprs.push_back("8 - 9");
        exprs.push_back("1 + 2");
        exprs.push_back("3 * 4");
        exprs.push_back("5 / 6");
        exprs.push_back("7 + 8");
        exprs.push_back("9 * 1");
        exprs.push_back("2 + 3");
        exprs.push_back("4 + 5");
        exprs.push_back("6 - 7");
        exprs.push_back("8 / 9");
        exprs.push_back("1 - 2");
        exprs.push_back("3 - 4");
        exprs.push_back("5 / 6");
        exprs.push_back("7 / 8");
        exprs.push_back("9 - 1");
        exprs.push_back("2 * 3");
        exprs.push_back("4 / 5");
        exprs.push_back("6 + 7");
        exprs.push_back("8 * 9");
        exprs.push_back("1 / 2");
        exprs.push_back("3 / 4");
        exprs.push_back("5 + 6");
        exprs.push_back("7 + 8");
        exprs.push_back("9 + 1");
        exprs.push_back("2 - 3");
        exprs.push_back("4 + 5");
        exprs.push_back("6 / 7");
        exprs.push_back("8 / 9");
        exprs.push_back("1 * 2");
        exprs.push_back("3 * 4");
        exprs.push_back("5 / 6");
        exprs.push_back("7 - 8");
        exprs.push_back("9 / 1");
        exprs.push_back("2 / 3");
        exprs.push_back("4 + 5");
        exprs.push_back("6 * 7");
        exprs.push_back("8 * 9");
        exprs.push_back("1 + 2");
        exprs.push_back("3 * 4");
        exprs.push_back("5 - 6");
        exprs.push_back("7 * 8");
        exprs.push_back("9 + 1");
        exprs.push_back("2 + 3");
        exprs.push_back("4 / 5");
        exprs.push_back("6 + 7");
        exprs.push_back("8 + 9");
        exprs.push_back("1 + 2");
        exprs.push_back("3 + 4");
        exprs.push_back("5 * 6");
        exprs.push_back("7 + 8");
        exprs.push_back("9 * 1");
        exprs.push_back("2 / 3");
        exprs.push_back("4 * 5");
        exprs.push_back("6 * 7");
        exprs.push_back("8 * 9");
        exprs.push_back("1 + 2");
        exprs.push_back("3 + 4");
        exprs.push_back("5 / 6");
        exprs.push_back("7 - 8");
        exprs.push_back("9 - 1");
        exprs.push_back("2 - 3");
        exprs.push_back("4 - 5");
        exprs.push_back("6 + 7");
        exprs.push_back("8 + 9");
        exprs.push_back("1 + 2");
        exprs.push_back("3 + 4");
        exprs.push_back("5 / 6");
        exprs.push_back("7 - 8");
        exprs.push_back("9 / 1");
        exprs.push_back("2 * 3");
        exprs.push_back("4 - 5");
        exprs.push_back("6 / 7");
        exprs.push_back("8 / 9");
        exprs.push_back("1 + 2");
        exprs.push_back("3 - 4");
        exprs.push_back("5 * 6");
        exprs.push_back("7 - 8");
        exprs.push_back("9 * 1");
        exprs.push_back("2 * 3");
        exprs.push_back("4 - 5");
        exprs.push_back("6 - 7");
        exprs.push_back("8 / 9");
        exprs.push_back("1 - 2");
        exprs.push_back("3 * 4");
        exprs.push_back("5 - 6");
        exprs.push_back("7 - 8");
        exprs.push_back("9 / 1");
        exprs.push_back("2 / 3");
        exprs.push_back("4 + 5");
        exprs.push_back("6 / 7");
        exprs.push_back("8 * 9");
        exprs.push_back("1 * 2");
        exprs.push_back("3 * 4");
        exprs.push_back("5 / 6");
        exprs.push_back("7 - 8");
        exprs.push_back("9 - 1");
        exprs.push_back("2 * 3");
        exprs.push_back("4 * 5");
        exprs.push_back("6 + 7");
        exprs.push_back("8 + 9");
        exprs.push_back("1 * 2");
        exprs.push_back("3 + 4");
        exprs.push_back("5 * 6");
        exprs.push_back("7 + 8");
        exprs.push_back("9 / 1");
        exprs.push_back("2 - 3");
        exprs.push_back("4 - 5");
        exprs.push_back("6 * 7");
        exprs.push_back("8 * 9");
        exprs.push_back("1 - 2");
        exprs.push_back("3 / 4");
        exprs.push_back("5 - 6");
        exprs.push_back("7 + 8");
        exprs.push_back("9 - 1");
        exprs.push_back("2 / 3");
        exprs.push_back("4 * 5");
        exprs.push_back("6 * 7");
        exprs.push_back("8 * 9");
        exprs.push_back("1 + 2");
        exprs.push_back("3 * 4");
        exprs.push_back("5 + 6");
        exprs.push_back("7 + 8");
        exprs.push_back("9 + 1");
        exprs.push_back("2 * 3");
        exprs.push_back("4 / 5");
        exprs.push_back("6 / 7");
        exprs.push_back("8 * 9");
        exprs.push_back("1 * 2");
        exprs.push_back("3 / 4");
        exprs.push_back("5 * 6");
        exprs.push_back("7 - 8");
        exprs.push_back("9 * 1");
        exprs.push_back("2 + 3");
        exprs.push_back("4 * 5");
        exprs.push_back("6 + 7");
        exprs.push_back("8 / 9");
        exprs.push_back("1 - 2");
        exprs.push_back("3 * 4");
        exprs.push_back("5 * 6");
        exprs.push_back("7 / 8");
        exprs.push_back("9 * 1");
        exprs.push_back("2 - 3");
        exprs.push_back("4 / 5");
        exprs.push_back("6 - 7");
        exprs.push_back("8 / 9");
        exprs.push_back("1 / 2");
        exprs.push_back("3 - 4");
        exprs.push_back("5 / 6");
        exprs.push_back("7 * 8");
        exprs.push_back("9 - 1");
        exprs.push_back("2 - 3");
        exprs.push_back("4 * 5");
        exprs.push_back("6 * 7");
        exprs.push_back("8 - 9");
        exprs.push_back("1 / 2");
        exprs.push_back("3 + 4");
        exprs.push_back("5 / 6");
        exprs.push_back("7 / 8");
        exprs.push_back("9 - 1");
        exprs.push_back("2 - 3");
        exprs.push_back("4 * 5");
        exprs.push_back("6 / 7");
        exprs.push_back("8 + 9");
        exprs.push_back("1 + 2");
        exprs.push_back("3 + 4");
        exprs.push_back("5 + 6");
        exprs.push_back("7 - 8");
        exprs.push_back("9 + 1");
        exprs.push_back("2 / 3");
        exprs.push_back("4 + 5");
        exprs.push_back("6 * 7");
        exprs.push_back("8 + 9");
        exprs.push_back("1 * 2");
        exprs.push_back("3 - 4");
        exprs.push_back("5 - 6");
        exprs.push_back("7 + 8");
        exprs.push_back("9 * 1");
        exprs.push_back("2 + 3");
        exprs.push_back("4 * 5");
        exprs.push_back("6 / 7");
        exprs.push_back("8 / 9");
        exprs.push_back("1 / 2");
        exprs.push_back("3 * 4");
        exprs.push_back("5 - 6");
        exprs.push_back("7 - 8");
        exprs.push_back("9 * 1");
        exprs.push_back("2 - 3");
        exprs.push_back("4 - 5");
        exprs.push_back("6 + 7");
        exprs.push_back("8 * 9");
        exprs.push_back("1 + 2");
        exprs.push_back("3 - 4");
        exprs.push_back("5 * 6");
        exprs.push_back("7 - 8");
        exprs.push_back("9 + 1");
        exprs.push_back("2 * 3");
        exprs.push_back("4 / 5");
        exprs.push_back("6 - 7");
        exprs.push_back("8 / 9");
        exprs.push_back("1 / 2");
        exprs.push_back("3 + 4");
        exprs.push_back("5 - 6");
        exprs.push_back("7 + 8");
        exprs.push_back("9 - 1");
        exprs.push_back("2 - 3");
        exprs.push_back("4 / 5");
        exprs.push_back("6 / 7");
        exprs.push_back("8 * 9");
        exprs.push_back("1 - 2");
        exprs.push_back("3 - 4");
        exprs.push_back("5 / 6");
        exprs.push_back("7 + 8");
        exprs.push_back("9 - 1");
        exprs.push_back("2 * 3");
        exprs.push_back("4 / 5");
        exprs.push_back("6 - 7");
        exprs.push_back("8 - 9");
        exprs.push_back("1 + 2");
        exprs.push_back("3 + 4");
        exprs.push_back("5 + 6");
        exprs.push_back("7 * 8");
        exprs.push_back("9 + 1");
        exprs.push_back("2 - 3");
        exprs.push_back("4 * 5");
        exprs.push_back("6 - 7");
        exprs.push_back("8 - 9");
        exprs.push_back("1 * 2");
        exprs.push_back("3 / 4");
        exprs.push_back("5 - 6");
        exprs.push_back("7 * 8");
        exprs.push_back("9 / 1");
        exprs.push_back("2 - 3");
        exprs.push_back("4 + 5");
        exprs.push_back("6 + 7");
        exprs.push_back("8 - 9");
        exprs.push_back("1 + 2");
        exprs.push_back("3 + 4");
        exprs.push_back("5 * 6");
        exprs.push_back("7 / 8");
        exprs.push_back("9 / 1");
        exprs.push_back("2 - 3");
        exprs.push_back("4 - 5");
        exprs.push_back("6 * 7");
        exprs.push_back("8 * 9");
        exprs.push_back("1 / 2");
        exprs.push_back("3 * 4");
        exprs.push_back("5 / 6");
        exprs.push_back("7 - 8");
        exprs.push_back("9 - 1");
        exprs.push_back("2 * 3");
        exprs.push_back("4 / 5");
        exprs.push_back("6 * 7");
        exprs.push_back("8 * 9");
        exprs.push_back("1 + 2");
        exprs.push_back("3 - 4");
        exprs.push_back("5 + 6");
        exprs.push_back("7 - 8");
        exprs.push_back("9 / 1");
        exprs.push_back("2 - 3");
        exprs.push_back("4 + 5");
        exprs.push_back("6 - 7");
        exprs.push_back("8 + 9");
        exprs.push_back("1 - 2");
        exprs.push_back("3 + 4");
        exprs.push_back("5 * 6");
        exprs.push_back("7 * 8");
        exprs.push_back("9 + 1");
        exprs.push_back("2 / 3");
        exprs.push_back("4 * 5");
        exprs.push_back("6 - 7");
        exprs.push_back("8 * 9");
        exprs.push_back("1 / 2");
        exprs.push_back("3 + 4");
        exprs.push_back("5 + 6");
        exprs.push_back("7 - 8");
        exprs.push_back("9 / 1");
        exprs.push_back("2 * 3");
        exprs.push_back("4 - 5");
        exprs.push_back("6 / 7");
        exprs.push_back("8 - 9");
        exprs.push_back("1 / 2");
        exprs.push_back("3 + 4");
        exprs.push_back("5 / 6");
        exprs.push_back("7 / 8");
        exprs.push_back("9 / 1");
        exprs.push_back("2 / 3");
        exprs.push_back("4 / 5");
        exprs.push_back("6 / 7");
        exprs.push_back("8 + 9");
        exprs.push_back("1 - 2");
        exprs.push_back("3 - 4");
        exprs.push_back("5 - 6");
        exprs.push_back("7 / 8");
        exprs.push_back("9 - 1");
        exprs.push_back("2 + 3");
        exprs.push_back("4 * 5");
        exprs.push_back("6 + 7");
        exprs.push_back("8 * 9");
        exprs.push_back("1 - 2");
        exprs.push_back("3 * 4");
        exprs.push_back("5 + 6");
        exprs.push_back("7 * 8");
        exprs.push_back("9 / 1");
        exprs.push_back("2 * 3");
        exprs.push_back("4 / 5");
        exprs.push_back("6 / 7");
        exprs.push_back("8 + 9");
        exprs.push_back("1 - 2");
        exprs.push_back("3 - 4");
        exprs.push_back("5 * 6");
        exprs.push_back("7 / 8");
        exprs.push_back("9 * 1");
        exprs.push_back("2 * 3");
        exprs.push_back("4 / 5");
        exprs.push_back("6 * 7");
        exprs.push_back("8 / 9");
        exprs.push_back("1 * 2");
        exprs.push_back("3 * 4");
        exprs.push_back("5 * 6");
        exprs.push_back("7 + 8");
        exprs.push_back("9 - 1");
        exprs.push_back("2 - 3");
        exprs.push_back("4 * 5");
        exprs.push_back("6 - 7");
        exprs.push_back("8 + 9");
        exprs.push_back("1 * 2");
        exprs.push_back("3 - 4");
        exprs.push_back("5 * 6");
        exprs.push_back("7 - 8");
        exprs.push_back("9 - 1");
        exprs.push_back("2 + 3");
        exprs.push_back("4 / 5");
        exprs.push_back("6 - 7");
        exprs.push_back("8 / 9");
        exprs.push_back("1 + 2");
        exprs.push_back("3 - 4");
        exprs.push_back("5 * 6");
        exprs.push_back("7 * 8");
        exprs.push_back("9 - 1");
        exprs.push_back("2 + 3");
        exprs.push_back("4 - 5");
        exprs.push_back("6 - 7");
        exprs.push_back("8 / 9");
        exprs.push_back("1 * 2");
        exprs.push_back("3 * 4");
        exprs.push_back("5 * 6");
        exprs.push_back("7 * 8");
        exprs.push_back("9 - 1");
        exprs.push_back("2 / 3");
        exprs.push_back("4 / 5");
        exprs.push_back("6 - 7");
        exprs.push_back("8 - 9");
        exprs.push_back("1 + 2");
        exprs.push_back("3 / 4");
        exprs.push_back("5 - 6");
        exprs.push_back("7 - 8");
        exprs.push_back("9 + 1");
        exprs.push_back("2 / 3");
        exprs.push_back("4 - 5");
        exprs.push_back("6 + 7");
        exprs.push_back("8 - 9");
        exprs.push_back("1 * 2");
        exprs.push_back("3 * 4");
        exprs.push_back("5 + 6");
        exprs.push_back("7 * 8");
        exprs.push_back("9 - 1");
        exprs.push_back("2 / 3");
        exprs.push_back("4 / 5");
        exprs.push_back("6 * 7");
        exprs.push_back("8 / 9");
        exprs.push_back("1 * 2");
        exprs.push_back("3 * 4");
        exprs.push_back("5 - 6");
        exprs.push_back("7 - 8");
        exprs.push_back("9 * 1");
        exprs.push_back("2 / 3");
        exprs.push_back("4 / 5");
        exprs.push_back("6 * 7");
        exprs.push_back("8 * 9");
        exprs.push_back("1 * 2");
        exprs.push_back("3 - 4");
        exprs.push_back("5 / 6");
        exprs.push_back("7 - 8");
        exprs.push_back("9 + 1");
        exprs.push_back("2 - 3");
        exprs.push_back("4 * 5");
        exprs.push_back("6 - 7");
        exprs.push_back("8 - 9");
        exprs.push_back("1 * 2");
        exprs.push_back("3 + 4");
        exprs.push_back("5 - 6");
        exprs.push_back("7 + 8");
        exprs.push_back("9 + 1");
        exprs.push_back("2 - 3");
        exprs.push_back("4 - 5");
        exprs.push_back("6 - 7");
        exprs.push_back("8 * 9");
        exprs.push_back("1 + 2");
        exprs.push_back("3 - 4");
        exprs.push_back("5 + 6");
        exprs.push_back("7 - 8");
        exprs.push_back("9 + 1");
        exprs.push_back("2 * 3");
        exprs.push_back("4 + 5");
        exprs.push_back("6 * 7");
        exprs.push_back("8 + 9");
        exprs.push_back("1 * 2");
        exprs.push_back("3 + 4");
        exprs.push_back("5 - 6");
        exprs.push_back("7 * 8");
        exprs.push_back("9 / 1");
        exprs.push_back("2 - 3");
        exprs.push_back("4 - 5");
        exprs.push_back("6 * 7");
        exprs.push_back("8 * 9");
        exprs.push_back("1 + 2");
        exprs.push_back("3 / 4");
        exprs.push_back("5 * 6");
        exprs.push_back("7 * 8");
        exprs.push_back("9 + 1");
        exprs.push_back("2 * 3");
        exprs.push_back("4 - 5");
        exprs.push_back("6 + 7");
        exprs.push_back("8 / 9");
        exprs.push_back("1 * 2");
        exprs.push_back("3 / 4");
        exprs.push_back("5 + 6");
        exprs.push_back("7 + 8");
        exprs.push_back("9 * 1");
        exprs.push_back("2 + 3");
        exprs.push_back("4 - 5");
        exprs.push_back("6 + 7");
        exprs.push_back("8 + 9");
        exprs.push_back("1 - 2");
        exprs.push_back("3 - 4");
        exprs.push_back("5 - 6");
        exprs.push_back("7 / 8");
        exprs.push_back("9 + 1");
        exprs.push_back("2 - 3");
        exprs.push_back("4 + 5");
        exprs.push_back("6 + 7");
        exprs.push_back("8 * 9");
        exprs.push_back("1 + 2");
        exprs.push_back("3 / 4");
        exprs.push_back("5 * 6");
        exprs.push_back("7 + 8");
        exprs.push_back("9 + 1");
        exprs.push_back("2 - 3");
        exprs.push_back("4 + 5");
        exprs.push_back("6 + 7");
        exprs.push_back("8 - 9");
        exprs.push_back("1 / 2");
        exprs.push_back("3 * 4");
        exprs.push_back("5 * 6");
        exprs.push_back("7 - 8");
        exprs.push_back("9 / 1");
        exprs.push_back("2 / 3");
        exprs.push_back("4 / 5");
        exprs.push_back("6 + 7");
        exprs.push_back("8 * 9");
        exprs.push_back("1 - 2");
        exprs.push_back("3 - 4");
        exprs.push_back("5 - 6");
        exprs.push_back("7 / 8");
        exprs.push_back("9 + 1");
        exprs.push_back("2 - 3");
        exprs.push_back("4 + 5");
        exprs.push_back("6 / 7");
        exprs.push_back("8 - 9");
        exprs.push_back("1 * 2");
        exprs.push_back("3 + 4");
        exprs.push_back("5 * 6");
        exprs.push_back("7 + 8");
        exprs.push_back("9 / 1");
        exprs.push_back("2 - 3");
        exprs.push_back("4 + 5");
        exprs.push_back("6 - 7");
        exprs.push_back("8 - 9");
        exprs.push_back("1 * 2");
        exprs.push_back("3 / 4");
        exprs.push_back("5 / 6");
        exprs.push_back("7 / 8");
        exprs.push_back("9 + 1");
        exprs.push_back("2 - 3");
        exprs.push_back("4 / 5");
        exprs.push_back("6 / 7");
        exprs.push_back("8 / 9");
        exprs.push_back("1 * 2");
        exprs.push_back("3 / 4");
        exprs.push_back("5 * 6");
        exprs.push_back("7 / 8");
        exprs.push_back("9 * 1");
        exprs.push_back("2 + 3");
        exprs.push_back("4 / 5");
        exprs.push_back("6 / 7");
        exprs.push_back("8 - 9");
        exprs.push_back("1 / 2");
        exprs.push_back("3 + 4");
        exprs.push_back("5 * 6");
        exprs.push_back("7 / 8");
        exprs.push_back("9 + 1");
        exprs.push_back("2 * 3");
        exprs.push_back("4 * 5");
        exprs.push_back("6 / 7");
        exprs.push_back("8 - 9");
        exprs.push_back("1 - 2");
        exprs.push_back("3 * 4");
        exprs.push_back("5 / 6");
        exprs.push_back("7 - 8");
        exprs.push_back("9 - 1");
        exprs.push_back("2 - 3");
        exprs.push_back("4 / 5");
        exprs.push_back("6 + 7");
        exprs.push_back("8 / 9");
        exprs.push_back("1 - 2");
        exprs.push_back("3 / 4");
        exprs.push_back("5 + 6");
        exprs.push_back("7 / 8");
        exprs.push_back("9 / 1");
        exprs.push_back("2 / 3");
        exprs.push_back("4 * 5");
        exprs.push_back("6 / 7");
        exprs.push_back("8 + 9");
        exprs.push_back("1 * 2");
        exprs.push_back("3 / 4");
        exprs.push_back("5 - 6");
        exprs.push_back("7 + 8");
        exprs.push_back("9 / 1");
        exprs.push_back("2 / 3");
        exprs.push_back("4 / 5");
        exprs.push_back("6 / 7");
        exprs.push_back("8 - 9");
        exprs.push_back("1 / 2");
        exprs.push_back("3 + 4");
        exprs.push_back("5 - 6");
        exprs.push_back("7 + 8");
        exprs.push_back("9 / 1");
        exprs.push_back("2 * 3");
        exprs.push_back("4 + 5");
        exprs.push_back("6 - 7");
        exprs.push_back("8 * 9");
        exprs.push_back("1 / 2");
        exprs.push_back("3 - 4");
        exprs.push_back("5 / 6");
        exprs.push_back("7 / 8");
        exprs.push_back("9 - 1");
        exprs.push_back("2 + 3");
        exprs.push_back("4 - 5");
        exprs.push_back("6 * 7");
        exprs.push_back("8 + 9");
        exprs.push_back("1 - 2");
        exprs.push_back("3 * 4");
        exprs.push_back("5 + 6");
        exprs.push_back("7 * 8");
        exprs.push_back("9 / 1");
        exprs.push_back("2 / 3");
        exprs.push_back("4 - 5");
        exprs.push_back("6 - 7");
        exprs.push_back("8 + 9");
        exprs.push_back("1 / 2");
        exprs.push_back("3 * 4");
        exprs.push_back("5 - 6");
        exprs.push_back("7 + 8");
        exprs.push_back("9 + 1");
        exprs.push_back("2 * 3");
        exprs.push_back("4 + 5");
        exprs.push_back("6 / 7");
        exprs.push_back("8 * 9");
        exprs.push_back("1 * 2");
        exprs.push_back("3 + 4");
        exprs.push_back("5 * 6");
        exprs.push_back("7 * 8");
        exprs.push_back("9 * 1");
        exprs.push_back("2 - 3");
        exprs.push_back("4 * 5");
        exprs.push_back("6 - 7");
        exprs.push_back("8 + 9");
        exprs.push_back("1 - 2");
        exprs.push_back("3 / 4");
        exprs.push_back("5 / 6");
        exprs.push_back("7 + 8");
        exprs.push_back("9 + 1");
        exprs.push_back("2 + 3");
        exprs.push_back("4 / 5");
        exprs.push_back("6 - 7");
        exprs.push_back("8 + 9");
        exprs.push_back("1 - 2");
        exprs.push_back("3 - 4");
        exprs.push_back("5 * 6");
        exprs.push_back("7 * 8");
        exprs.push_back("9 / 1");
        exprs.push_back("2 / 3");
        exprs.push_back("4 - 5");
        exprs.push_back("6 / 7");
        exprs.push_back("8 / 9");
        exprs.push_back("1 - 2");
        exprs.push_back("3 * 4");
        exprs.push_back("5 * 6");
        exprs.push_back("7 - 8");
        exprs.push_back("9 / 1");
        exprs.push_back("2 * 3");
        exprs.push_back("4 / 5");
        exprs.push_back("6 + 7");
        exprs.push_back("8 * 9");
        exprs.push_back("1 / 2");
        exprs.push_back("3 - 4");
        exprs.push_back("5 / 6");
        exprs.push_back("7 + 8");
        exprs.push_back("9 / 1");
        exprs.push_back("2 - 3");
        exprs.push_back("4 + 5");
        exprs.push_back("6 + 7");
        exprs.push_back("8 / 9");
        exprs.push_back("1 - 2");
        exprs.push_back("3 - 4");
        exprs.push_back("5 * 6");
        exprs.push_back("7 - 8");
        exprs.push_back("9 + 1");
        exprs.push_back("2 + 3");
        exprs.push_back("4 / 5");
        exprs.push_back("6 / 7");
        exprs.push_back("8 / 9");
        exprs.push_back("1 + 2");
        exprs.push_back("3 * 4");
        exprs.push_back("5 - 6");
        exprs.push_back("7 + 8");
        exprs.push_back("9 * 1");
        exprs.push_back("2 / 3");
        exprs.push_back("4 / 5");
        exprs.push_back("6 * 7");
        exprs.push_back("8 / 9");
        exprs.push_back("1 - 2");
        exprs.push_back("3 / 4");
        exprs.push_back("5 * 6");
        exprs.push_back("7 * 8");
        exprs.push_back("9 + 1");
        exprs.push_back("2 - 3");
        exprs.push_back("4 - 5");
        exprs.push_back("6 * 7");
        exprs.push_back("8 + 9");
        exprs.push_back("1 + 2");
        exprs.push_back("3 + 4");
        exprs.push_back("5 * 6");
        exprs.push_back("7 - 8");
        exprs.push_back("9 * 1");
        exprs.push_back("2 - 3");
        exprs.push_back("4 - 5");
        exprs.push_back("6 + 7");
        exprs.push_back("8 - 9");
        exprs.push_back("1 / 2");
        exprs.push_back("3 / 4");
        exprs.push_back("5 * 6");
        exprs.push_back("7 + 8");
        exprs.push_back("9 - 1");
        exprs.push_back("2 + 3");
        exprs.push_back("4 + 5");
        exprs.push_back("6 - 7");
        exprs.push_back("8 + 9");
        exprs.push_back("1 - 2");
        exprs.push_back("3 / 4");
        exprs.push_back("5 + 6");
        exprs.push_back("7 + 8");
        exprs.push_back("9 + 1");
        exprs.push_back("2 / 3");
        exprs.push_back("4 * 5");
        exprs.push_back("6 - 7");
        exprs.push_back("8 - 9");
        exprs.push_back("1 + 2");
        exprs.push_back("3 - 4");
        exprs.push_back("5 / 6");
        exprs.push_back("7 - 8");
        exprs.push_back("9 - 1");
        exprs.push_back("2 / 3");
        exprs.push_back("4 / 5");
        exprs.push_back("6 * 7");
        exprs.push_back("8 - 9");
        exprs.push_back("1 / 2");
        exprs.push_back("3 - 4");
        exprs.push_back("5 - 6");
        exprs.push_back("7 / 8");
        exprs.push_back("9 / 1");
        exprs.push_back("2 + 3");
        exprs.push_back("4 / 5");
        exprs.push_back("6 - 7");
        exprs.push_back("8 + 9");
        exprs.push_back("1 - 2");
        exprs.push_back("3 / 4");
        exprs.push_back("5 - 6");
        exprs.push_back("7 + 8");
        exprs.push_back("9 + 1");
        exprs.push_back("2 * 3");
        exprs.push_back("4 - 5");
        exprs.push_back("6 * 7");
        exprs.push_back("8 / 9");
        exprs.push_back("1 - 2");
        exprs.push_back("3 * 4");
        exprs.push_back("5 - 6");
        exprs.push_back("7 - 8");
        exprs.push_back("9 + 1");
        exprs.push_back("2 + 3");
        exprs.push_back("4 * 5");
        exprs.push_back("6 + 7");
        exprs.push_back("8 - 9");
        exprs.push_back("1 / 2");
        exprs.push_back("3 + 4");
        exprs.push_back("5 + 6");
        exprs.push_back("7 / 8");
        exprs.push_back("9 * 1");
        exprs.push_back("2 * 3");
        exprs.push_back("4 - 5");
        exprs.push_back("6 + 7");
        exprs.push_back("8 - 9");
        exprs.push_back("1 + 2");
        exprs.push_back("3 / 4");
        exprs.push_back("5 * 6");
        exprs.push_back("7 * 8");
        exprs.push_back("9 + 1");
        exprs.push_back("2 - 3");
        exprs.push_back("4 - 5");
        exprs.push_back("6 * 7");
        exprs.push_back("8 + 9");
        exprs.push_back("1 / 2");
        exprs.push_back("3 / 4");
        exprs.push_back("5 - 6");
        exprs.push_back("7 + 8");
        exprs.push_back("9 - 1");
        exprs.push_back("2 * 3");
        exprs.push_back("4 + 5");
        exprs.push_back("6 - 7");
        exprs.push_back("8 - 9");
        exprs.push_back("1 + 2");
        exprs.push_back("3 * 4");
        exprs.push_back("5 - 6");
        exprs.push_back("7 + 8");
        exprs.push_back("9 - 1");
        exprs.push_back("2 / 3");
        exprs.push_back("4 / 5");
        exprs.push_back("6 * 7");
        exprs.push_back("8 - 9");
        exprs.push_back("1 - 2");
        exprs.push_back("3 + 4");
        exprs.push_back("5 - 6");
        exprs.push_back("7 - 8");
        exprs.push_back("9 - 1");
        exprs.push_back("2 + 3");
        exprs.push_back("4 - 5");
        exprs.push_back("6 / 7");
        exprs.push_back("8 * 9");
        exprs.push_back("1 / 2");
        exprs.push_back("3 * 4");
        exprs.push_back("5 * 6");
        exprs.push_back("7 - 8");
        exprs.push_back("9 / 1");
        exprs.push_back("2 - 3");
        exprs.push_back("4 / 5");
        exprs.push_back("6 * 7");
        exprs.push_back("8 / 9");
        exprs.push_back("1 + 2");
        exprs.push_back("3 / 4");
        exprs.push_back("5 * 6");
        exprs.push_back("7 * 8");
        exprs.push_back("9 * 1");
        exprs.push_back("2 / 3");
        exprs.push_back("4 * 5");
        exprs.push_back("6 * 7");
        exprs.push_back("8 / 9");
        exprs.push_back("1 / 2");
        exprs.push_back("3 + 4");
        exprs.push_back("5 - 6");
        exprs.push_back("7 * 8");
        exprs.push_back("9 + 1");
        exprs.push_back("2 - 3");
        exprs.push_back("4 + 5");
        exprs.push_back("6 - 7");
        exprs.push_back("8 / 9");
        exprs.push_back("1 / 2");
        exprs.push_back("3 + 4");
        exprs.push_back("5 - 6");
        exprs.push_back("7 * 8");
        exprs.push_back("9 + 1");
        exprs.push_back("2 * 3");
        exprs.push_back("4 + 5");
        exprs.push_back("6 - 7");
        exprs.push_back("8 + 9");
        exprs.push_back("1 / 2");
        exprs.push_back("3 / 4");
        exprs.push_back("5 / 6");
        exprs.push_back("7 - 8");
        exprs.push_back("9 * 1");
        exprs.push_back("2 - 3");
        exprs.push_back("4 + 5");
        exprs.push_back("6 - 7");
        exprs.push_back("8 - 9");
        exprs.push_back("1 / 2");
        exprs.push_back("3 / 4");
        exprs.push_back("5 * 6");
        exprs.push_back("7 / 8");
        exprs.push_back("9 - 1");
        exprs.push_back("2 - 3");
        exprs.push_back("4 - 5");
        exprs.push_back("6 + 7");
        exprs.push_back("8 / 9");
        exprs.push_back("1 - 2");
        exprs.push_back("3 + 4");
        exprs.push_back("5 / 6");
        exprs.push_back("7 - 8");
        exprs.push_back("9 / 1");
        exprs.push_back("2 / 3");
        exprs.push_back("4 * 5");
        exprs.push_back("6 + 7");
        exprs.push_back("8 / 9");
        exprs.push_back("1 * 2");
        exprs.push_back("3 + 4");
        exprs.push_back("5 / 6");
        exprs.push_back("7 / 8");
        exprs.push_back("9 * 1");
        exprs.push_back("2 / 3");
        exprs.push_back("4 - 5");
        exprs.push_back("6 * 7");
        exprs.push_back("8 - 9");
        exprs.push_back("1 * 2");
        exprs.push_back("3 - 4");
        exprs.push_back("5 + 6");
        exprs.push_back("7 + 8");
        exprs.push_back("9 + 1");
        exprs.push_back("2 + 3");
        exprs.push_back("4 / 5");
        exprs.push_back("6 + 7");
        exprs.push_back("8 / 9");
        exprs.push_back("1 * 2");
        exprs.push_back("3 + 4");
        exprs.push_back("5 + 6");
        exprs.push_back("7 - 8");
        exprs.push_back("9 * 1");
        exprs.push_back("2 / 3");
        exprs.push_back("4 / 5");
        exprs.push_back("6 - 7");
        exprs.push_back("8 + 9");
        exprs.push_back("1 - 2");
        exprs.push_back("3 * 4");
        exprs.push_back("5 / 6");
        exprs.push_back("7 - 8");
        exprs.push_back("9 / 1");
        exprs.push_back("2 - 3");
        exprs.push_back("4 * 5");
        exprs.push_back("6 * 7");
        exprs.push_back("8 + 9");
        exprs.push_back("1 / 2");
        exprs.push_back("3 / 4");
        exprs.push_back("5 * 6");
        exprs.push_back("7 + 8");
        exprs.push_back("9 / 1");
        exprs.push_back("2 * 3");
        exprs.push_back("4 * 5");
        exprs.push_back("6 - 7");
        exprs.push_back("8 / 9");
        exprs.push_back("1 + 2");
        exprs.push_back("3 * 4");
        exprs.push_back("5 + 6");
        exprs.push_back("7 + 8");
        exprs.push_back("9 + 1");
        exprs.push_back("2 * 3");
        exprs.push_back("4 + 5");
        exprs.push_back("6 - 7");
        exprs.push_back("8 + 9");
        exprs.push_back("1 * 2");
        exprs.push_back("3 * 4");
        exprs.push_back("5 - 6");
        exprs.push_back("7 - 8");
        exprs.push_back("9 + 1");
        exprs.push_back("2 + 3");
        exprs.push_back("4 * 5");
        exprs.push_back("6 + 7");
        exprs.push_back("8 - 9");
        exprs.push_back("1 - 2");
        exprs.push_back("3 + 4");
        exprs.push_back("5 / 6");
        exprs.push_back("7 / 8");
        exprs.push_back("9 + 1");
        exprs.push_back("2 / 3");
        exprs.push_back("4 * 5");
        exprs.push_back("6 * 7");
        exprs.push_back("8 - 9");
        exprs.push_back("1 / 2");
        exprs.push_back("3 / 4");
        exprs.push_back("5 - 6");
        exprs.push_back("7 - 8");
        exprs.push_back("9 * 1");
        exprs.push_back("2 * 3");
        exprs.push_back("4 + 5");
        exprs.push_back("6 - 7");
        exprs.push_back("8 + 9");
        exprs.push_back("1 / 2");
        exprs.push_back("3 + 4");
        exprs.push_back("5 + 6");
        exprs.push_back("7 * 8");
        exprs.push_back("9 * 1");
        exprs.push_back("2 / 3");
        exprs.push_back("4 * 5");
        exprs.push_back("6 / 7");
        exprs.push_back("8 / 9");
        exprs.push_back("1 / 2");
        exprs.push_back("3 * 4");
        exprs.push_back("5 - 6");
        exprs.push_back("7 / 8");
        exprs.push_back("9 * 1");
        exprs.push_back("2 * 3");
        exprs.push_back("4 - 5");
        exprs.push_back("6 + 7");
        exprs.push_back("8 - 9");
        exprs.push_back("1 * 2");
        exprs.push_back("3 / 4");
        exprs.push_back("5 * 6");
        exprs.push_back("7 - 8");
        exprs.push_back("9 * 1");
        exprs.push_back("2 + 3");
        exprs.push_back("4 + 5");
        exprs.push_back("6 * 7");
        exprs.push_back("8 + 9");
        exprs.push_back("1 - 2");
        exprs.push_back("3 + 4");
        exprs.push_back("5 / 6");
        exprs.push_back("7 * 8");
        exprs.push_back("9 * 1");
        exprs.push_back("2 / 3");
        exprs.push_back("4 * 5");
        exprs.push_back("6 * 7");
        exprs.push_back("8 + 9");
        exprs.push_back("1 - 2");
        exprs.push_back("3 * 4");
        exprs.push_back("5 + 6");
        exprs.push_back("7 - 8");
        exprs.push_back("9 - 1");
        exprs.push_back("2 / 3");
        exprs.push_back("4 - 5");
        exprs.push_back("6 * 7");
        exprs.push_back("8 * 9");
        exprs.push_back("1 / 2");
        exprs.push_back("3 + 4");
        exprs.push_back("5 - 6");
        exprs.push_back("7 + 8");
        exprs.push_back("9 / 1");
        exprs.push_back("2 / 3");
        exprs.push_back("4 - 5");
        exprs.push_back("6 * 7");
        exprs.push_back("8 + 9");
        exprs.push_back("1 - 2");
        exprs.push_back("3 / 4");
        exprs.push_back("5 * 6");
        exprs.push_back("7 - 8");
        exprs.push_back("9 + 1");
        exprs.push_back("2 - 3");
        exprs.push_back("4 + 5");
        exprs.push_back("6 * 7");
        exprs.push_back("8 / 9");
        exprs.push_back("1 * 2");
        exprs.push_back("3 + 4");
        exprs.push_back("5 * 6");
        exprs.push_back("7 + 8");
        exprs.push_back("9 + 1");
        exprs.push_back("4 * 5");
        exprs.push_back("2 * 3");
        exprs.push_back("4 * 5");

        int i = 1;

        el::c_expr_dup_checker checker;
        for (auto& e : exprs) {
            checker.add_expr(e, i++);
        }

        auto info = checker.dump_statistics();

        std::cout << info << std::endl;

        getchar();
    }
};